### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by Flygsand** [PretendoNetwork/website#101]
I'm interested in implementing password reset. The below is for a browser-based flow. I have no idea how this could be done from a Wii U console. The API part is here: PretendoNetwork/account#21

I suggest two new forms

## Start flow
Currently linked from the log in form, but broken.

**URL:** https://pretendo.network/account/passwordreset
**Parameters:** none
**Fields:** `email`, `captcha_response`
**Corresponding API endpoint:** `/v1/passwordreset`

## Update password
To be linked from password reset e-mail.

**URL:** https://pretendo.network/account/password
**Parameters:** `access_token`
**Fields**: `password`, `password_confirm`
**Corresponding API endpoint:** `/v1/password`

I threw this together pretty quickly so there's probably a lot to be desired. I'd be happy to receive any input, suggestions, ideas, etc. that you might have.

**Comment by jonbarrow** [comment]
Cleaning up some old issues. Closed as complete, as password resets have been implemented for a while now
