### ISSUE TITLE
Cannot display error-code documentation: /doc/.../errors/

### ISSUE THREAD

**Issue by Gandalf1783** [PretendoNetwork/website#167]
Calling e.g. https://pretendo.network/docs/en_US/errors/JXT-598-0010 fails with "Cannot GET /docs/en_US/errors/JXT-598-0010".

Steps to reproduce:
Click on one of the error-codes in the "Error-Code" section.

**Comment by ashmonty** [comment]
Thank you, fixed with 3f23708b11766d6f6a51988d447575c707e6fdeb!
