### ISSUE TITLE
Support for FIDO2 Authentication for User Accounts

### ISSUE THREAD

**Issue by CorruptedPhazite** [PretendoNetwork/website#184]
Adding FIDO2 to accounts would provide a number of benefits including:

- Support for passwordless, second-factor and multi-factor authentication
- Significantly improved account protection from phishing attacks
- Streamlined user onboarding and sign in experience (if passwordless authentication is enabled)

**Comment by jonbarrow** [comment]
Going through some older issues to clean stuff up. I don't see how this would work here? Users need a password, this isn't something that can be removed. You need to be able to access the account via a console, so we can't just remove password authentication?

**Comment by jonbarrow** [comment]
Closing until further details about how this would work are provided. Seems like an invalid feature request at this time
