### ISSUE TITLE
Password check

### ISSUE THREAD

**Issue by Docmine17** [PretendoNetwork/website#195]
The Password popup for "Download account files" doesn't check if the password is correct and the textbox is invisible.
![image](https://user-images.githubusercontent.com/67164552/218282616-da01a339-b2a3-4fc4-8b4b-25b4028c4f55.png)

Wrong password result in a "Cemu Pretendo Online Files.zip" that don't work, when you put them in cemu it doesn't connect to the Pretendo network:

![image](https://user-images.githubusercontent.com/67164552/218282577-d035b7e2-f4a1-4447-8ce3-e466199fbd9d.png)
Error-Code: 102-2932

It is possible to download the files even without entering the password.

**Comment by jonbarrow** [comment]
Closing this as the "download account files" feature for Cemu is now deprecated, and will be removed in a future update. Our servers already do not work with these files anymore
