### ISSUE TITLE
Setting up Pretendo with Cemu / Guide not updated

### ISSUE THREAD

**Issue by Exilorian** [PretendoNetwork/website#219]
The guide to setup Pretendo on Cemu is not updated, the guide says "Cemu requires the use of several files obtained via dumping from real hardware. You may use those files if you have a physical Wii U, they will work just fine when connecting to Pretendo. If you don't have a real Wii U navigate to [your account page](https://pretendo.network/account) and select Download account files", when, you can't download your files anymore from the Pretendo Account Page, this "feature" was apparently removed due to being abused by hackers or something. To avoid misleading beginners, please update the guide to the current info.

**Comment by jonbarrow** [comment]
The docs have been updated
