### ISSUE TITLE
Update references to FBI in 3DS docs

### ISSUE THREAD

**Issue by jonbarrow** [PretendoNetwork/website#253]
Steveice10 has completely nuked his GitHub account, seemingly completely out of the blue. The reason for this is unknown right now but I think it's safe to assume it's because of the Yuzu lawsuit and the fate of Citra.

With the loss of Steveice10, we also have now lost the official FBI repository. Our documentation for the 3DS references this now dead repository.

I'm hesitant to just start linking to random forks/mirrors, as we don't want to inadvertently recommend users install something unsafe onto their systems. Thoughts on how to move forward?

@hauntii @shutterbug2000 @DaniElectra

**Comment by DaniElectra** [comment]
We can use the repo that hacks.guide is now using: https://github.com/lifehackerhansol/FBI

The account is a trusted developer and it's a member of the hacks.guide organization

**Comment by jonbarrow** [comment]
That works for me, I hadn't thought about checking if they'd updated yet or not

**Comment by ExperiencersInternational** [comment]
> Steveice10 has completely nuked his GitHub account, seemingly completely out of the blue. The reason for this is unknown right now but I think it's safe to assume it's because of the Yuzu lawsuit and the fate of Citra.
> 
> With the loss of Steveice10, we also have now lost the official FBI repository. Our documentation for the 3DS references this now dead repository.
> 
> I'm hesitant to just start linking to random forks/mirrors, as we don't want to inadvertently recommend users install something unsafe onto their systems. Thoughts on how to move forward?
> 
> @hauntii @shutterbug2000 @DaniElectra

That genuinely sucks, surprised they deleted their account though considering the lawsuit was very clearly targeting Switch emulation. Nintendo doesn't support the 3DS now afaik in any major capacity except online for the next 32 days.

**Comment by gitlimes** [comment]
> We can use the repo that hacks.guide is now using: https://github.com/lifehackerhansol/FBI

Just checked, and it appears that that repository has been archived, presumably also because of the Yuzu lawsuit.

**Comment by shutterbug2000** [comment]
Nah, I think that's just because they don't plan on making source changes and also don't want people opening issues/PRs

**Comment by jonbarrow** [comment]
> > We can use the repo that hacks.guide is now using: [lifehackerhansol/FBI](https://github.com/lifehackerhansol/FBI)
> 
> Just checked, and it appears that that repository has been archived, presumably also because of the Yuzu lawsuit.

The original repository was also archived iirc. It was considered feature complete

**Comment by ExperiencersInternational** [comment]
> Nah, I think that's just because they don't plan on making source changes and also don't want people opening issues/PRs

To be honest I don't actually see Nintendo causing anything in the future for FBI to warrant updates, works well as it is right now

**Comment by DaniElectra** [comment]
Done in #254
