### ISSUE TITLE
Feature request: Status page for the servers

### ISSUE THREAD

**Issue by Bjorkan** [PretendoNetwork/website#270]
## Why?
A question often asked on the discord is if the servers are online or not, which made me think that maybe a dedicated part of the website could be a status page where maintenance and other issues regarding the operation of the servers could be a nice addition to have. It makes it easy for us regular players to be able to see if there is maintenance on any servers or if something random has made them go offline :)

[Uptime Kuma](https://github.com/louislam/uptime-kuma) is one software I personally use and has worked great for me! I don't know how it would work in a more public setting but I assume similar software should be easy to find. 

## Example sites
https://www.nintendo.co.jp/netinfo/en_US/index.html
https://steamstat.us/

Thank you for this amazing project and I look forward to seeing it grow <3

**Comment by Bjorkan** [comment]
> Something like this is on the todo list, we just don't have a timeline for it since it's a fairly low priority compared to other stuff we have to get done. But it WILL be coming eventually

Wonderful! Great to hear! 🎉 Do you want me to close this issue or should I leave it open? 😄

**Comment by ExperiencersInternational** [comment]
Already filed months ago here lol

https://github.com/PretendoNetwork/website/issues/227

**Comment by Bjorkan** [comment]
> Already filed months ago here lol
> 
> 
> 
> https://github.com/PretendoNetwork/website/issues/227

Yep! You are right! Totally missed that! My bad! #227 is almodt identical! Will close this one in favour of that one! 🥰

**Comment by jonbarrow** [comment]
Closed as completed, since this is planned
