### ISSUE TITLE
BUG: Japanese account menu text broken (mobile)

### ISSUE THREAD

**Issue by reindex-ot** [PretendoNetwork/website#279]
layout is broken in Japanese.
![Screenshot_2024-04-15-20-49-57-582_com android chrome](https://github.com/PretendoNetwork/website/assets/32851879/93b2830a-eafd-4928-b7ce-4b7700f1c398)
![Screenshot_2024-04-15-20-49-47-795_com android chrome](https://github.com/PretendoNetwork/website/assets/32851879/ae4ebdc8-6c0c-4679-a225-c1b630290fc1)

**Comment by Silver-Volt4** [comment]
Should be fixed when dev is merged into main

**Comment by reindex-ot** [comment]
nice.

**Comment by gitlimes** [comment]
Yup, this issue has been fixed, the patch just isn't live yet. Closing this
