### ISSUE TITLE
Adding list of error codes?

### ISSUE THREAD

**Issue by Yevnilc-S-C** [PretendoNetwork/website#280]
As someone who does some support in the discord server, I can comfortably say that finding what error codes mean is a huge pain, and bandwidth is a struggle to work with sometimes due to the lack of known error codes at the moment, which is why I think it would be a good idea to include a section on the website with error codes, likely sorted by the first 3 digits (022, 001, etc) similar to how the bandwidth bot is organized, this would also be beneficial for bandwidth production as some errors (022-5432 for example), take a lot to explain, and would likely be easier for people to follow if there was a link to a fix, instead of a compacted bandwidth message. That's why I think adding a section like this would be beneficial to both the developers who work on bandwidth, and the people in the server who help out in the support channel. Thank you!

**Comment by jonbarrow** [comment]
This is implemented at https://pretendo.network/docs/errors. It pulls data from https://github.com/PretendoNetwork/error-codes for the pages
