### ISSUE TITLE
PNID cannot be the same as NNID warning on 3ds docs

### ISSUE THREAD

**Issue by RISC-VLIW** [PretendoNetwork/website#290]
I believe a warning should be added on the 3ds docs to ensure nobody makes this issue as it is just a hassle to deal with, as well as no account deletion being a thing, so it's just a mess to deal with.
right now the login/acc creation section of the doc reads:
"The 3DS does not rely on NNIDs for the vast majority of it's game servers. Because of this, using a PNID is also not required for most games

Setting up a PNID on the 3DS is the same as setting up a NNID. You may either create the PNID on your console, or register from an account 

It is recommended to register the PNID on your device at this time, as registering on the website does not currently allow you to change your user data"

This currently doesn't make it clear that the PNID cannot be the same as the NNID, and I think there should be something added on the docs to make it clear to make life easier for everyone. Thank you

**Comment by RISC-VLIW** [comment]
Often times, people with a 3ds to sign in don't have a wii u, so it's unintuitive to have it on one doc and not the other, as most 3ds users will not read the wii u docs

**Comment by marvinjoa** [comment]
I agree with this!
Neither the 3DS nor the Sign Up page have this warning and BOTH should have the same warning as the WiiU page does.

> Often times, people with a 3ds to sign in don't have a wii u, so it's unintuitive to have it on one doc and not the other, as most 3ds users will not read the wii u docs

Yup! Wasn’t the 3DS sold significantly more than the WiiU anyway? I don’t understand why the 3DS page is being neglected like this, considering the potential users it has vs the WiiU ones.

**Comment by ExperiencersInternational** [comment]
> I agree with this! Neither the 3DS nor the Sign Up page have this warning and BOTH should have the same warning as the WiiU page does.
> 
> > Often times, people with a 3ds to sign in don't have a wii u, so it's unintuitive to have it on one doc and not the other, as most 3ds users will not read the wii u docs
> 
> Yup! Wasn’t the 3DS sold significantly more than the WiiU anyway? I don’t understand why the 3DS page is being neglected like this, considering the potential users it has vs the WiiU ones.

It's not being neglected, the team at Pretendo is just busy. Surprised this hasn't been added yet
