### ISSUE TITLE
Wii U installation guide should make it clear that SSSL doesn't currently work 

### ISSUE THREAD

**Issue by ExperiencersInternational** [PretendoNetwork/website#302]
With the recent issues with SSSL, the Wii U installation guide should make it clear that you need to install CFW to your Wii U for the time being until it is back up.

**Comment by jonbarrow** [comment]
This is incorrect. SSSL does work. It's just that there's issues with BOSS specifically. This only really affects Splatoon. All other titles that we otherwise support still function as normal with SSSL

**Comment by ExperiencersInternational** [comment]
> This is incorrect. SSSL does work. It's just that there's issues with BOSS specifically. This only really affects Splatoon. All other titles that we otherwise support still function as normal with SSSL

Still, I find it necessary to indicate that Splatoon doesn't work since I come across a lot of people wondering why Splatoon isn't working when they're still using SSSL.

**Comment by jonbarrow** [comment]
I disagree. Updating the website itself for arbitrary announcements is not the way to go imo, and requires us to manually maintain that and clutter the git history with essentially useless commits. We have made various announcements and acknowledgments on our social medias and other online presences already.

**Comment by ExperiencersInternational** [comment]
I don't think people always necessarily look at announcements on social media etc, they will try and get support without doing research beforehand which would explain why Splatoon or any other game isn't working for them.

Closing issue anyways since I guess it's unnecessary.
