### ISSUE TITLE
[Enhancement]: Mention the Settings app in the instructions for linking a PNID to a 3DS

### ISSUE THREAD

**Issue by upadsamay387** [PretendoNetwork/website#316]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What enhancement would you like to see?

There isn't an indication of where to go to link a PNID

**Comment by jonbarrow** [comment]
This is incorrect. The guide very clearly states:

> Setting up a PNID on the 3DS is the same as setting up a NNID

Which indicates that to link a PNID, you use the same system on your console that you would use for a NNID. No further direction is needed here. I am not particularly interested in walking the user through every minor step as if they've never touched a console before. We have to assume some level of competency and cut off where we hold the users hands, or else the guides will eventually contain a surplus of information that is useless to the average user and harm the guides readability

**Comment by upadsamay387** [comment]
There's a reason that I specified "where" and not "how." Linking an NNID was a one-and-done deal, and for most people, this was done years ago. Therefore, I don't think it's an issue of competency to find _where_ the link option is. My suggested fix was to reword a sentence to mention the Settings app, and given how brief of a fix it is, I don't see how it would lead to a bloated guide.

**Comment by jonbarrow** [comment]
"Where" and "how" go hand in hand here. The guide clearly states that it's done in the same way as you would a NNID. This is more than enough information for the vast majority of users, and for those who still do not understand it provides more than enough direction to find the "where".

> given how brief of a fix it is, I don't see how it would lead to a bloated guide.

I did not say that this specific request would lead to that, alone. I said; `We have to assume some level of competency and cut off where we hold the users hands, or else the guides will eventually contain a surplus of information that is useless to the average user and harm the guides readability`.

It's called creep. If we continually allow for changes like this, which alone may be small and do not bloat the guide, then *eventually* the guide will become bloated with useless information. So an assumption about the users understanding has to be made, and we cut off providing information beyond that. Your one request may only change a few lines or words, but if we allowed 100 changes like this you can easily see how things get out of hand.
