### ISSUE TITLE
[Bug]: Discord invite link is still redirecting to invite gg

### ISSUE THREAD

**Issue by TheMispeled** [PretendoNetwork/website#339]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What happened?

When you click on any discord invite link, it redirects to invite gg which apparently has been down for 3 months. 

### What did you expect to happen?

To join the discord server. 

### Steps to reproduce?

1. Click on any discord invite link
2. See cloudfare error

**Comment by Negative2010** [comment]
All I can recommend is using [discord.gg/pretendo](https://discord.gg/pretendo) instead. What was the point of using invite.gg?

**Comment by ashquarky** [comment]
Thanks for reporting this, it's fixed and should be live next time we refresh the site
